version: '3'
services:
  blockchain-explorer:
    container_name: blockchain-explorer
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "10500:80"
    healthcheck:
      test: curl --fail -s http://danilojakob.ch:10500 || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
